on:
  schedule:
    # Esegue ogni giorno alle 8 UTC
    - cron: "*/2 * * * *"

jobs:
  scheduling:
    runs-on: ubuntu-latest
    name: Pulizia Sessioni
    
    steps:
      - name: Info 
        run: echo "this is my scheduling job"
