on:
  schedule:
    # Esegue ogni giorno alle 8 UTC
    - cron: "*/2 * * * *"
  
  # Permetti esecuzione manuale dal tab Actions
  workflow_dispatch:

jobs:
  scheduling:
    runs-on: ubuntu-latest
    name: Pulizia Sessioni
    
    steps:
      - name: Info 
        run: echo "this is my scheduling job"
